spring:
  h2:
    console:
      enabled: true
      path: /h2console/
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=TRUE;MODE=MySQL
    username: sa
    password:
    driverClassName: org.h2.Driver
